// ignore_for_file: avoid_unnecessary_containers, prefer_const_constructors, prefer_const_literals_to_create_immutables, prefer_final_fields

import 'package:country_picker/country_picker.dart';
import 'package:dropdown_button2/dropdown_button2.dart';
import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:practice_flutter_2/components/button.dart';
import 'package:practice_flutter_2/components/dropdown_button.dart';
import 'package:practice_flutter_2/components/text_field.dart';
import 'package:practice_flutter_2/pages/home_page.dart';

class dataTokoPage extends StatefulWidget {
  @override
  State<dataTokoPage> createState() => _dataTokoPageState();
}

class _dataTokoPageState extends State<dataTokoPage> {
  String? _selectedJenisUsaha;

  final tokoController = TextEditingController();
  final alamatController = TextEditingController();

  final List<String> jenisUsaha = [
    "Pilih jenis usaha..",
    "Apotek/Toko Obat & Kecantikan",
    "Bengkel & Carwash",
    "Counter Pulsa & Handphone",
    "Jasa/Service Lainnya",
    "Laundry",
    "Makanan & Minuman",
    "Minimarket/Toko Kelontong/Warung",
    "Online Shop",
    "Persewaan/Rental/Studio Foto",
    "Pertanian",
    "Salon, Spa, Barbershop",
    "Service Elektronik",
    "Toko Alat Tulis/Fotokopi",
    "Toko Bangunan",
    "Toko Elektronik",
    "Toko Lainnya",
    "Toko Pakaian dan Aksesoris"
  ];

  final List<String> negara = [
    "Afghanistan (AF)",
    "Åland Islands (AX)",
    "Albania (AL)",
    "Algeria (DZ)",
    "American Samoa (AS)",
    "Andorra (AD)",
    "Angola (AO)",
    "Anguilla (AI)",
    "Antarctica (AQ)",
    "Antigua & Barbuda (AG)",
    "Argentina (AR)",
    "Armenia (AM)",
    "Aruba (AW)",
    "Australia (AU)",
    "Austria (AT)",
    "Azerbaijan (AZ)",
    "Bahamas (BS)",
    "Bahrain (BH)",
    "Bangladesh (BD)",
    "Barbados (BB)",
    "Belarus (BY)",
    "Belgium (BE)",
    "Belize (BZ)",
    "Benin (BJ)",
    "Bermuda (BM)",
    "Bhutan (BT)",
    "Bolivia (BO)",
    "Bosnia & Herzegovina (BA)",
    "Botswana (BW)",
    "Bouvet Island (BV)",
    "Brazil (BR)",
    "British Indian Ocean Territory (IO)",
    "British Virgin Islands (VG)",
    "Brunei (BN)",
    "Bulgaria (BG)",
    "Burkina Faso (BF)",
    "Burundi (BI)",
    "Cambodia (KH)",
    "Cameroon (CM)",
    "Canada (CA)",
    "Cape Verde (CV)",
    "Caribbean Netherlands (BQ)",
    "Cayman Islands (KY)",
    "Central African Republic (CF)",
    "Chad (TD)",
    "Chile (CL)",
    "China (CN)",
    "Christmas Island (CX)",
    "Cocos (Keeling) Islands (CC)",
    "Colombia (CO)",
    "Comoros (KM)",
    "Congo - Brazzaville (CG)",
    "Congo - Kinshasa (CD)",
    "Cook Islands (CK)",
    "Costa Rica (CR)",
    "Côte d’Ivoire (CI)",
    "Croatia (HR)",
    "Cuba (CU)",
    "Curaçao (CW)",
    "Cyprus (CY)",
    "Czechia (CZ)",
    "Denmark (DK)",
    "Djibouti (DJ)",
    "Dominica (DM)",
    "Dominican Republic (DO)",
    "Ecuador (EC)",
    "Egypt (EG)",
    "El Salvador (SV)",
    "Equatorial Guinea (GQ)",
    "Eritrea (ER)",
    "Estonia (EE)",
    "Eswatini (SZ)",
    "Ethiopia (ET)",
    "Falkland Islands (FK)",
    "Faroe Islands (FO)",
    "Fiji (FJ)",
    "Finland (FI)",
    "France (FR)",
    "French Guiana (GF)",
    "French Polynesia (PF)",
    "French Southern Territories (TF)",
    "Gabon (GA)",
    "Gambia (GM)",
    "Georgia (GE)",
    "Germany (DE)",
    "Ghana (GH)",
    "Gibraltar (GI)",
    "Greece (GR)",
    "Greenland (GL)",
    "Grenada (GD)",
    "Guadeloupe (GP)",
    "Guam (GU)",
    "Guatemala (GT)",
    "Guernsey (GG)",
    "Guinea (GN)",
    "Guinea-Bissau (GW)",
    "Guyana (GY)",
    "Haiti (HT)",
    "Heard & McDonald Islands (HM)",
    "Honduras (HN)",
    "Hong Kong SAR China (HK)",
    "Hungary (HU)",
    "Iceland (IS)",
    "India (IN)",
    "Indonesia (ID)",
    "Iran (IR)",
    "Iraq (IQ)",
    "Ireland (IE)",
    "Isle of Man (IM)",
    "Israel (IL)",
    "Italy (IT)",
    "Jamaica (JM)",
    "Japan (JP)",
    "Jersey (JE)",
    "Jordan (JO)",
    "Kazakhstan (KZ)",
    "Kenya (KE)",
    "Kiribati (KI)",
    "Kuwait (KW)",
    "Kyrgyzstan (KG)",
    "Laos (LA)",
    "Latvia (LV)",
    "Lebanon (LB)",
    "Lesotho (LS)",
    "Liberia (LR)",
    "Libya (LY)",
    "Liechtenstein (LI)",
    "Lithuania (LT)",
    "Luxembourg (LU)",
    "Macao SAR China (MO)",
    "Madagascar (MG)",
    "Malawi (MW)",
    "Malaysia (MY)",
    "Maldives (MV)",
    "Mali (ML)",
    "Malta (MT)",
    "Marshall Islands (MH)",
    "Martinique (MQ)",
    "Mauritania (MR)",
    "Mauritius (MU)",
    "Mayotte (YT)",
    "Mexico (MX)",
    "Micronesia (FM)",
    "Moldova (MD)",
    "Monaco (MC)",
    "Mongolia (MN)",
    "Montenegro (ME)",
    "Montserrat (MS)",
    "Morocco (MA)",
    "Mozambique (MZ)",
    "Myanmar (Burma) (MM)",
    "Namibia (NA)",
    "Nauru (NR)",
    "Nepal (NP)",
    "Netherlands (NL)",
    "New Caledonia (NC)",
    "New Zealand (NZ)",
    "Nicaragua (NI)",
    "Niger (NE)",
    "Nigeria (NG)",
    "Niue (NU)",
    "Norfolk Island (NF)",
    "North Korea (KP)",
    "North Macedonia (MK)",
    "Northern Mariana Islands (MP)",
    "Norway (NO)",
    "Oman (OM)",
    "Pakistan (PK)",
    "Palau (PW)",
    "Palestinian Territories (PS)",
    "Panama (PA)",
    "Papua New Guinea (PG)",
    "Paraguay (PY)",
    "Peru (PE)",
    "Philippines (PH)",
    "Pitcairn Islands (PN)",
    "Poland (PL)",
    "Portugal (PT)",
    "Puerto Rico (PR)",
    "Qatar (QA)",
    "Réunion (RE)",
    "Romania (RO)",
    "Russia (RU)",
    "Rwanda (RW)",
    "Samoa (WS)",
    "San Marino (SM)",
    "São Tomé & Príncipe (ST)",
    "Saudi Arabia (SA)",
    "Senegal (SN)",
    "Serbia (RS)",
    "Seychelles (SC)",
    "Sierra Leone (SL)",
    "Singapore (SG)",
    "Sint Maarten (SX)",
    "Slovakia (SK)",
    "Slovenia (SI)",
    "Solomon Islands (SB)",
    "Somalia (SO)",
    "South Africa (ZA)",
    "South Georgia & South Sandwich Islands (GS)",
    "South Korea (KR)",
    "South Sudan (SS)",
    "Spain (ES)",
    "Sri Lanka (LK)",
    "St. Barthélemy (BL)",
    "St. Helena (SH)",
    "St. Kitts & Nevis (KN)",
    "St. Lucia (LC)",
    "St. Martin (MF)",
    "St. Pierre & Miquelon (PM)",
    "St. Vincent & Grenadines (VC)",
    "Sudan (SD)",
    "Suriname (SR)",
    "Svalbard & Jan Mayen (SJ)",
    "Sweden (SE)",
    "Switzerland (CH)",
    "Syria (SY)",
    "Taiwan (TW)",
    "Tajikistan (TJ)",
    "Tanzania (TZ)",
    "Thailand (TH)",
    "Timor-Leste (TL)",
    "Togo (TG)",
    "Tokelau (TK)",
    "Tonga (TO)",
    "Trinidad & Tobago (TT)",
    "Tunisia (TN)",
    "Turkey (TR)",
    "Turkmenistan (TM)",
    "Turks & Caicos Islands (TC)",
    "Tuvalu (TV)",
    "U.S. Outlying Islands (UM)"
        "U.S. Virgin Islands (VI)",
    "Uganda (UG)",
    "Ukraine (UA)",
    "United Arab Emirates (AE)",
    "United Kingdom (GB)",
    "United States (US)",
    "Uruguay (UY)",
    "Uzbekistan (UZ)",
    "Vanuatu (VU)",
    "Vatican City (VA)",
    "Venezuela (VE)",
    "Vietnam (VN)",
    "Wallis & Futuna (WF)",
    "Western Sahara (EH)",
    "Yemen (YE)",
    "Zambia (ZM)",
    "Zimbabwe (ZW)"
  ];

  final List<String> provinsi = [
    "Aceh (NAD)",
    "Sumatera Utara",
    "Sumatera Barat",
    "Riau",
    "Jambi",
    "Sumatera Selatan",
    "Bengkulu",
    "Lampung",
    "Kepulauan Bangka Belitung",
    "Kepulauan Riau",
    "DKI Jakarta",
    "Jawa Barat",
    "Jawa Tengah",
    "DI Yogyakarta",
    "Jawa Timur",
    "Banten",
    "Bali",
    "Nusa Tenggara Barat (NTB)",
    "Nusa Tenggara Timur (NTT)",
    "Kalimantan Barat",
    "Kalimantan Tengah",
    "Kalimantan Selatan",
    "Kalimantan Timur",
    "Kalimantan Utara",
    "Sulawesi Utara",
    "Sulawesi Tengah",
    "Sulawesi Selatan",
    "Sulawesi Tenggara",
    "Gorontalo",
    "Sulawesi Barat",
    "Maluku",
    "Maluku Utara",
    "Papua",
    "Papua Barat",
    "Papua Selatan",
    "Papua Tengah",
    "Papua Pegunungan",
    "Papua Barat Daya",
  ];

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Container(
        child: Column(
          children: [
            Expanded(
              child: Container(
                color: Colors.green,
                child: Center(
                  child: Text(
                    'DATA TOKO',
                    style: TextStyle(
                      color: Colors.white,
                      fontWeight: FontWeight.w500,
                      fontSize: 25,
                      fontFamily: 'Montserrat',
                    ),
                  ),
                ),
              ),
            ),
            Expanded(
              flex: 4,
              child: Container(
                color: Colors.grey,
                child: Column(
                  children: [
                    ButtonDropDown(
                        hint: 'Pilih jenis usaha..', choices: jenisUsaha),
                    SizedBox(
                      height: 25,
                    ),
                    My_TextField(
                      hintText: 'Masukan Nama Toko/Usaha',
                      obscureText: false,
                      labelText: 'Nama Toko/Usaha',
                      controller: tokoController,
                    ),
                    SizedBox(
                      height: 25,
                    ),
                    Align(
                      alignment: Alignment.centerLeft,
                      child: Padding(
                        padding: const EdgeInsets.only(left: 35),
                        child: Text(
                          'Negara',
                          style: TextStyle(
                            color: Colors.black,
                          ),
                        ),
                      ),
                    ),
                    SizedBox(
                      height: 25,
                    ),
                    ButtonDropDown(
                      hint: 'Pilih negara',
                      choices: negara,
                    ),
                    SizedBox(
                      height: 25,
                    ),
                    ButtonDropDown(
                      hint: 'Pilih provinsi',
                      choices: provinsi,
                    ),
                    SizedBox(
                      height: 25,
                    ),
                    My_TextField(
                      hintText: "Masukkan Alamat",
                      obscureText: false,
                      labelText: "Alamat",
                      controller: alamatController,
                    ),
                  ],
                ),
              ),
            ),
            Expanded(
              flex: 1,
              child: Container(
                color: Colors.red,
                child: Column(
                  children: [
                    GestureDetector(
                      onTap: () {
                        Navigator.push(
                          context,
                          MaterialPageRoute(
                            builder: (context) => HomePage(),
                          ),
                        );
                      },
                      child: MyButton(
                        buttonText: 'SIGN UP',
                        colorButton: Colors.black,
                        colorText: Colors.white,
                        Width: 330,
                        Height: 60,
                      ),
                    ),
                  ],
                ),
              ),
            ),
          ],
        ),
      ),
    );
  }
}
